// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VIRS.Infra.DataBase.EFCoreSqlServer;

#nullable disable

namespace VIRS.Infra.DataBase.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120212001_Add_Image_Table")]
    partial class Add_Image_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VIRS.Domain.Core.CarAgg.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManufactureYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("CarOwnerId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("VIRS.Domain.Core.CarModelAgg.Entities.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "Family", "Name")
                        .IsUnique();

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "405 GLX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "405 SLX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "پارس"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "پارس TU5"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "پارس LX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "پارس XU7P"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "206 Type 2"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "206 Type 5"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "206 SD V8"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "207i دستی"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "207i اتوماتیک"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "207i پانوراما"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "207i MC"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Family = "پژو",
                            Manufacturer = "ایرانخودرو",
                            Name = "207i SD"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            Family = "سمند",
                            Manufacturer = "ایرانخودرو",
                            Name = "LX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Family = "سمند",
                            Manufacturer = "ایرانخودرو",
                            Name = "LX EF7"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Family = "سمند",
                            Manufacturer = "ایرانخودرو",
                            Name = "EF7 بنزینی"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Family = "سمند",
                            Manufacturer = "ایرانخودرو",
                            Name = "EF7 دوگانه‌سوز"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Family = "سمند",
                            Manufacturer = "ایرانخودرو",
                            Name = "SE"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Family = "سورن",
                            Manufacturer = "ایرانخودرو",
                            Name = "ELX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Family = "سورن",
                            Manufacturer = "ایرانخودرو",
                            Name = "ELX EF7"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Family = "سورن",
                            Manufacturer = "ایرانخودرو",
                            Name = "پلاس"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Family = "دنا",
                            Manufacturer = "ایرانخودرو",
                            Name = "عادی"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Family = "دنا",
                            Manufacturer = "ایرانخودرو",
                            Name = "پلاس"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Family = "دنا",
                            Manufacturer = "ایرانخودرو",
                            Name = "پلاس توربو"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001a"),
                            Family = "دنا",
                            Manufacturer = "ایرانخودرو",
                            Name = "پلاس 6 سرعته"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001b"),
                            Family = "رانا",
                            Manufacturer = "ایرانخودرو",
                            Name = "عادی"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001c"),
                            Family = "رانا",
                            Manufacturer = "ایرانخودرو",
                            Name = "پلاس"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001d"),
                            Family = "تارا",
                            Manufacturer = "ایرانخودرو",
                            Name = "V1 دستی"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001e"),
                            Family = "تارا",
                            Manufacturer = "ایرانخودرو",
                            Name = "V2 اتوماتیک"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001f"),
                            Family = "تارا",
                            Manufacturer = "ایرانخودرو",
                            Name = "LX"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Family = "تارا",
                            Manufacturer = "ایرانخودرو",
                            Name = "6AT جدید"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "111"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "131"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "132"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "141"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "SE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Family = "پراید",
                            Manufacturer = "سایپا",
                            Name = "LE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Family = "تیبا",
                            Manufacturer = "سایپا",
                            Name = "صندوق‌دار"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Family = "تیبا",
                            Manufacturer = "سایپا",
                            Name = "2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Family = "تیبا",
                            Manufacturer = "سایپا",
                            Name = "SX"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            Family = "تیبا",
                            Manufacturer = "سایپا",
                            Name = "EX"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            Family = "ساینا",
                            Manufacturer = "سایپا",
                            Name = "عادی"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000c"),
                            Family = "ساینا",
                            Manufacturer = "سایپا",
                            Name = "EX"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000d"),
                            Family = "ساینا",
                            Manufacturer = "سایپا",
                            Name = "SX"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000e"),
                            Family = "ساینا",
                            Manufacturer = "سایپا",
                            Name = "پلاس"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000f"),
                            Family = "ساینا",
                            Manufacturer = "سایپا",
                            Name = "پلاس اتوماتیک"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "عادی"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "S"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "GX"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "GXR"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "اتوماتیک"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            Family = "کوئیک",
                            Manufacturer = "سایپا",
                            Name = "R اتوماتیک"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            Family = "شاهین",
                            Manufacturer = "سایپا",
                            Name = "S"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            Family = "شاهین",
                            Manufacturer = "سایپا",
                            Name = "G"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            Family = "شاهین",
                            Manufacturer = "سایپا",
                            Name = "اتوماتیک"
                        });
                });

            modelBuilder.Entity("VIRS.Domain.Core.CarOwnerAgg.Entities.CarOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("NID")
                        .IsUnique();

                    b.ToTable("CarOwners");
                });

            modelBuilder.Entity("VIRS.Domain.Core.ImageAgg.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InspectionRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRequestId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("VIRS.Domain.Core.InspectionRequestAgg.Entities.InspectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcceptable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CarOwnerId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasFilter("[TrackingNumber] IS NOT NULL");

                    b.ToTable("InspectionRequests");
                });

            modelBuilder.Entity("VIRS.Domain.Core.SystemAdminAgg.Entities.SystemAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemAdmins_Username");

                    b.ToTable("SystemsAdmins");
                });

            modelBuilder.Entity("VIRS.Domain.Core.CarAgg.Entities.Car", b =>
                {
                    b.HasOne("VIRS.Domain.Core.CarModelAgg.Entities.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VIRS.Domain.Core.CarOwnerAgg.Entities.CarOwner", "CarOwner")
                        .WithMany("Cars")
                        .HasForeignKey("CarOwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("VIRS.Domain.Core.CarAgg.Entities.LicensePlate", "Plate", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FirstPart")
                                .HasMaxLength(2)
                                .IsUnicode(true)
                                .HasColumnType("int")
                                .HasColumnName("PlateFirstPart");

                            b1.Property<string>("Letter")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PlateLetter");

                            b1.Property<int>("ProvinceCode")
                                .HasMaxLength(2)
                                .IsUnicode(true)
                                .HasColumnType("int")
                                .HasColumnName("PlateProvinceCode");

                            b1.Property<int>("SecondPart")
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("int")
                                .HasColumnName("PlateSecondPart");

                            b1.HasKey("CarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.Navigation("CarModel");

                    b.Navigation("CarOwner");

                    b.Navigation("Plate")
                        .IsRequired();
                });

            modelBuilder.Entity("VIRS.Domain.Core.ImageAgg.Entities.Image", b =>
                {
                    b.HasOne("VIRS.Domain.Core.InspectionRequestAgg.Entities.InspectionRequest", "InspectionRequest")
                        .WithMany("Images")
                        .HasForeignKey("InspectionRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InspectionRequest");
                });

            modelBuilder.Entity("VIRS.Domain.Core.InspectionRequestAgg.Entities.InspectionRequest", b =>
                {
                    b.HasOne("VIRS.Domain.Core.CarAgg.Entities.Car", "Car")
                        .WithMany("InspectionRequests")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VIRS.Domain.Core.CarOwnerAgg.Entities.CarOwner", "CarOwner")
                        .WithMany("inspectionRequests")
                        .HasForeignKey("CarOwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarOwner");
                });

            modelBuilder.Entity("VIRS.Domain.Core.CarAgg.Entities.Car", b =>
                {
                    b.Navigation("InspectionRequests");
                });

            modelBuilder.Entity("VIRS.Domain.Core.CarOwnerAgg.Entities.CarOwner", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("inspectionRequests");
                });

            modelBuilder.Entity("VIRS.Domain.Core.InspectionRequestAgg.Entities.InspectionRequest", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
